/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.Mecanico;
import aplicacion.Reparacion;
import aplicacion.Repuesto;
import aplicacion.Subordinado;
import aplicacion.TipoReparacion;
import aplicacion.Vehiculo;
import java.util.ArrayList;

/**
 *
 * @author alumnogreibd
 */
public class VAnhadirMecanico extends javax.swing.JDialog {
    
    private VVehiculo padre;
    private aplicacion.FachadaAplicacion fa;
    private Subordinado subseleccionado;


    /**
     * Creates new form VNuevaReparacion
     */
    public VAnhadirMecanico (VVehiculo parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.padre = parent;
        this.fa = fa;
        initComponents();
        
        generarListas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        disponiblesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ocupadosTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelarBoton = new javax.swing.JButton();
        botonDerecha = new javax.swing.JButton();
        botonIzquierda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Reparación");

        disponiblesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(disponiblesTable);

        ocupadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ocupadosTable);

        jLabel1.setText("Disponibles:");

        jLabel2.setText("Ocupados:");

        cancelarBoton.setText("Cancelar");
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        botonDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.jpg"))); // NOI18N
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });

        botonIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.jpg"))); // NOI18N
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonDerecha)
                            .addComponent(botonIzquierda))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelarBoton)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(botonDerecha)
                        .addGap(29, 29, 29)
                        .addComponent(botonIzquierda))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarBoton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        ModeloListaStrings mRC;
     ModeloListaStrings mC;

     mRC = (ModeloListaStrings) disponiblesList.getModel();
     mC = (ModeloListaStrings) ocupadosList.getModel();
     mRC.nuevoElemento(mC.getElementAt(ocupadosList.getSelectedIndex()));
     mRC.nuevoId(mC.getIdAt(ocupadosList.getSelectedIndex()));
     mC.borrarElemento(ocupadosList.getSelectedIndex());
             
     if (mC.getSize()==0) botonIzquierda.setEnabled(false);
     else {
         ocupadosList.setSelectedIndex(0);
         nombreTextField.setText(disponiblesList.getSelectedValue());
     }
     disponiblesList.setSelectedIndex(mRC.getSize()-1);
     botonDerecha.setEnabled(true);
    }//GEN-LAST:event_botonIzquierdaActionPerformed

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
        ModeloListaStrings mRC;
     ModeloListaStrings mC;

     mRC = (ModeloListaStrings) disponiblesList.getModel();
     mC = (ModeloListaStrings) ocupadosList.getModel();
    if (esNumeroValido(cantidadTextField.getText())) {
        mC.nuevoElemento(mRC.getElementAt(disponiblesList.getSelectedIndex()));
        mC.nuevoId(mRC.getIdAt(disponiblesList.getSelectedIndex()));
        mRC.borrarElemento(disponiblesList.getSelectedIndex());
        if (mRC.getSize()==0) botonDerecha.setEnabled(false);
        else {
            disponiblesList.setSelectedIndex(0);
            nombreTextField.setText(disponiblesList.getSelectedValue());
        }
        ocupadosList.setSelectedIndex(mC.getSize()-1);
        botonIzquierda.setEnabled(true);
        errorCantidad.setVisible(false);
     } else errorCantidad.setVisible(true);
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDerecha;
    private javax.swing.JButton botonIzquierda;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JTable disponiblesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ocupadosTable;
    // End of variables declaration//GEN-END:variables

    private void generarListas() {
        
    }
}
