/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Categoria;
import aplicacion.FachadaAplicacion;
import java.util.List;

/**
 *
 * @author alumnogreibd
 */
public class VCategorias extends javax.swing.JDialog {
    FachadaAplicacion fa;
    /**
     * Creates new form VCategorias
     */
    public VCategorias(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        initComponents();
        
        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CategoriasList = new javax.swing.JList<>();
        CategoriasLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        NombreTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescripcionTextArea = new javax.swing.JTextArea();
        DescripcionLabel = new javax.swing.JLabel();
        AnadirButton = new javax.swing.JButton();
        BorrarButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Categorías");

        CategoriasList.setModel(new ModeloListaStrings());
        CategoriasList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriasListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CategoriasList);

        CategoriasLabel.setText("Categorías");

        NombreLabel.setText("Nombre:");

        DescripcionTextArea.setColumns(20);
        DescripcionTextArea.setRows(5);
        jScrollPane2.setViewportView(DescripcionTextArea);

        DescripcionLabel.setText("Descripción");

        AnadirButton.setText("Añadir");
        AnadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirButtonActionPerformed(evt);
            }
        });

        BorrarButton.setText("Borrar");
        BorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarButtonActionPerformed(evt);
            }
        });

        SalirButton.setText("Salir");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(AnadirButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BorrarButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(NombreLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(NombreTextField))
                                .addComponent(DescripcionLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SalirButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(CategoriasLabel)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(CategoriasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NombreLabel)
                                    .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(DescripcionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AnadirButton)
                                    .addComponent(BorrarButton))
                                .addGap(92, 92, 92)))
                        .addComponent(SalirButton)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirButtonActionPerformed
        Categoria cat;
        String nombre=NombreTextField.getText();
        String descripcion=DescripcionTextArea.getText();
        
        if(!nombre.isEmpty() && !descripcion.isEmpty()) {
            cat=new Categoria(nombre, descripcion);
//            fa.crearCategoria(cat);
        }
        actualizarLista();
        NombreTextField.setText("");
        DescripcionTextArea.setText("");
    }//GEN-LAST:event_AnadirButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void BorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarButtonActionPerformed
        String cat;
        
        if(CategoriasList.getSelectedIndex()>-1) {
            cat=((ModeloListaStrings) CategoriasList.getModel()).getElementAt(CategoriasList.getSelectedIndex());
//            fa.borrarCategoria(cat);
            actualizarLista();
        }
    }//GEN-LAST:event_BorrarButtonActionPerformed

    private void CategoriasListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriasListMouseClicked
        ModeloListaStrings m;
        m=(ModeloListaStrings) CategoriasList.getModel();
        
        String cat = m.getElementAt(CategoriasList.getSelectedIndex());
        String descripcion = new String();
        
//        List<Categoria> categorias = fa.obtenerCategorias();
        List<Categoria> categorias = null;
        
        for(Categoria c : categorias)
            if(c.getNombre().equals(cat))
                descripcion=c.getDescripcion();
        
        NombreTextField.setText(cat);
        DescripcionTextArea.setText(descripcion);
    }//GEN-LAST:event_CategoriasListMouseClicked

    private void actualizarLista() {
        List<Categoria> categorias;
        List<String> stringcat = new java.util.ArrayList<String>();
        
        
//      categorias = fa.obtenerCategorias();
         categorias = null;
        
        for(Categoria cat : categorias)
            stringcat.add(cat.getNombre());
        
        ModeloListaStrings mListaC=new ModeloListaStrings();
        CategoriasList.setModel(mListaC);
        //mListaC.setElementos(stringcat);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirButton;
    private javax.swing.JButton BorrarButton;
    private javax.swing.JLabel CategoriasLabel;
    private javax.swing.JList<String> CategoriasList;
    private javax.swing.JLabel DescripcionLabel;
    private javax.swing.JTextArea DescripcionTextArea;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JButton SalirButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
