package gui;

import aplicacion.EmpleadoPracticas;
import aplicacion.FachadaAplicacion;
import aplicacion.JefeTaller;
import aplicacion.Mecanico;
import java.awt.Frame;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author alumnogreibd
 */
public class VEmpleados extends javax.swing.JDialog {
    private FachadaAplicacion fa;
    private Frame parent;
    /**
     * Creates new form VEmpleados
     */
    public VEmpleados(java.awt.Frame parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.fa = fa;
        this.parent = parent;
    }
    
    public java.awt.Frame getParent(){
        return this.parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panelEmpleados = new javax.swing.JTabbedPane();
        panelMecánicos = new javax.swing.JPanel();
        buscaId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboOrdenar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMecanicos = new javax.swing.JTable();
        botonContratar = new javax.swing.JButton();
        botonDespedir = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        panelPrácticas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buscaNombreTutor = new javax.swing.JTextField();
        botonBuscarPracticas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPracticas = new javax.swing.JTable();
        botonAñadirPracticas = new javax.swing.JButton();
        botonEliminarPracticas = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buscaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ordena por:");

        comboOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Sueldo asc.", "Sueldo desc." }));
        comboOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrdenarActionPerformed(evt);
            }
        });

        tablaMecanicos.setModel(new gui.ModeloTablaMecanicos());
        jScrollPane1.setViewportView(tablaMecanicos);

        botonContratar.setText("Contratar");
        botonContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContratarActionPerformed(evt);
            }
        });

        botonDespedir.setText("Despedir");
        botonDespedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDespedirActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMecánicosLayout = new javax.swing.GroupLayout(panelMecánicos);
        panelMecánicos.setLayout(panelMecánicosLayout);
        panelMecánicosLayout.setHorizontalGroup(
            panelMecánicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMecánicosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelMecánicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMecánicosLayout.createSequentialGroup()
                        .addComponent(botonContratar)
                        .addGap(18, 18, 18)
                        .addComponent(botonDespedir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEditar))
                    .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMecánicosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelMecánicosLayout.setVerticalGroup(
            panelMecánicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMecánicosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelMecánicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(comboOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMecánicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonContratar)
                    .addComponent(botonDespedir)
                    .addComponent(botonEditar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelEmpleados.addTab("Mecánicos", panelMecánicos);

        jLabel3.setText("Nombre del tutor:");

        botonBuscarPracticas.setText("Buscar");
        botonBuscarPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPracticasActionPerformed(evt);
            }
        });

        tablaPracticas.setModel(new ModeloTablaPracticas());
        jScrollPane2.setViewportView(tablaPracticas);

        botonAñadirPracticas.setText("Añadir");

        botonEliminarPracticas.setText("Eliminar");
        botonEliminarPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPracticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrácticasLayout = new javax.swing.GroupLayout(panelPrácticas);
        panelPrácticas.setLayout(panelPrácticasLayout);
        panelPrácticasLayout.setHorizontalGroup(
            panelPrácticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrácticasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelPrácticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrácticasLayout.createSequentialGroup()
                        .addComponent(botonAñadirPracticas)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarPracticas))
                    .addGroup(panelPrácticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelPrácticasLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(buscaNombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(146, 146, 146)
                            .addComponent(botonBuscarPracticas))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelPrácticasLayout.setVerticalGroup(
            panelPrácticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrácticasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelPrácticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buscaNombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarPracticas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrácticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadirPracticas)
                    .addComponent(botonEliminarPracticas))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelEmpleados.addTab("Empleados de prácticas", panelPrácticas);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEmpleados))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaIdActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        this.buscarMecanicos();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void comboOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrdenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOrdenarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonDespedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDespedirActionPerformed
        // TODO add your handling code here:
        Mecanico m = getMecanicoSeleccionado();
        if(m!=null){
            if(!fa.despedirMecanico(m.getIdMecanico())){
                VAviso va = new VAviso(this.parent, true, "El empleado que se desea borrar tiene acciones pendiente y no es posible");
                va.setVisible(true);
            }
            else{
                ModeloTablaMecanicos mm;
                mm=(ModeloTablaMecanicos) tablaMecanicos.getModel();
                mm.borrarMecanico(tablaMecanicos.getSelectedRow());
            }
        }
    }//GEN-LAST:event_botonDespedirActionPerformed

    private void botonContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContratarActionPerformed
        // TODO add your handling code here:
        VNuevoMecanico vn = new VNuevoMecanico(this, true, this.fa);
        vn.setVisible(true);
        buscarMecanicos();
    }//GEN-LAST:event_botonContratarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        Mecanico m = getMecanicoSeleccionado();
        if (m!=null){
            VNuevoMecanico vn = new VNuevoMecanico(this, true, this.fa, m);
            vn.setVisible(true);
        }
        buscarMecanicos();
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonBuscarPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPracticasActionPerformed
        // TODO add your handling code here:
        buscarPracticas();
    }//GEN-LAST:event_botonBuscarPracticasActionPerformed

    private void botonEliminarPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPracticasActionPerformed
        // TODO add your handling code here:
        EmpleadoPracticas e = getPracticasSeleccionado();
        if(e!=null){
            if(!fa.despedirPracticas(e.getIdalumno()){
                VAviso va = new VAviso(this.parent, true, "El empleado de prácticas está asistiendo a una reparación y no se puede despedir");
                va.setVisible(true);
            }
            else{
                ModeloTablaPracticas m;
                m=(ModeloTablaPracticas) tablaPracticas.getModel();
                m.borrarEmpleadoPracticas(tablaPracticas.getSelectedRow());
            }
        }
    }//GEN-LAST:event_botonEliminarPracticasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadirPracticas;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonBuscarPracticas;
    private javax.swing.JButton botonContratar;
    private javax.swing.JButton botonDespedir;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminarPracticas;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField buscaId;
    private javax.swing.JTextField buscaNombreTutor;
    private javax.swing.JComboBox<String> comboOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane panelEmpleados;
    private javax.swing.JPanel panelMecánicos;
    private javax.swing.JPanel panelPrácticas;
    private javax.swing.JTable tablaMecanicos;
    private javax.swing.JTable tablaPracticas;
    // End of variables declaration//GEN-END:variables

    public void buscarMecanicos(){
        ModeloTablaMecanicos m;
        m=(ModeloTablaMecanicos) tablaMecanicos.getModel();
        
        m.setFilas(fa.buscarMecanicos(buscaId.getText(),(String) comboOrdenar.getSelectedItem()));
        if (m.getRowCount() > 0) {
            tablaMecanicos.setRowSelectionInterval(0, 0);
            tablaMecanicos.requestFocus();
            botonDespedir.setEnabled(true);
            botonEditar.setEnabled(true);
        } else{
            botonDespedir.setEnabled(false);
            botonEditar.setEnabled(false);
        }
    }
    
    public void buscarPracticas(){
        ModeloTablaPracticas m;

        m=(ModeloTablaPracticas) tablaPracticas.getModel();
        m.setFilas(fa.buscarPracticas(buscaNombreTutor.getText()));
        if (m.getRowCount() > 0) {
            tablaPracticas.setRowSelectionInterval(0, 0);
        }
    }
    
    public Mecanico getMecanicoSeleccionado(){
        Mecanico m = null;
        int i = tablaMecanicos.getSelectedRow();
        
        if(i>-1) {
            m=((ModeloTablaMecanicos) tablaMecanicos.getModel()).obtenerMecanico(i);
        }
        return m;
    }
    
    public EmpleadoPracticas getPracticasSeleccionado(){
        EmpleadoPracticas e = null;
        int i = tablaPracticas.getSelectedRow();
        
        if(i>-1) {
            e=((ModeloTablaPracticas) tablaPracticas.getModel()).obtenerEmpleadoPracticas(i);
        }
        return e;
    }
    
}
