/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.Mecanico;
import aplicacion.Reparacion;
import aplicacion.Repuesto;
import aplicacion.TipoReparacion;
import aplicacion.Vehiculo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alumnogreibd
 */
public class VNuevaReparacion extends javax.swing.JDialog {
    
    private VVehiculo padre;
    private aplicacion.FachadaAplicacion fa;
    private Vehiculo vehiculo;
    private Mecanico mecanico;

    /**
     * Creates new form VNuevaReparacion
     */
    public VNuevaReparacion(VVehiculo parent, boolean modal, FachadaAplicacion fa, Vehiculo vehiculo, Mecanico mecanico) {
        super(parent, modal);
        this.padre = parent;
        this.fa = fa;
        this.vehiculo = vehiculo;
        this.mecanico=mecanico;
        initComponents();
        setLocationRelativeTo(null);


        generarListas();
        setBotones();
        setComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstRestoRepuestos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRepuestosReparacion = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cantidadTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tipoReparacionComboBox = new javax.swing.JComboBox<>();
        anhadirBoton = new javax.swing.JButton();
        cancelarBoton = new javax.swing.JButton();
        botonDerecha = new javax.swing.JButton();
        botonIzquierda = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        errorCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Reparación");

        lstRestoRepuestos.setModel(new ModeloListaStrings());
        lstRestoRepuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstRestoRepuestosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstRestoRepuestos);

        lstRepuestosReparacion.setModel(new ModeloListaStrings());
        lstRepuestosReparacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstRepuestosReparacionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstRepuestosReparacion);

        jLabel1.setText("Repuestos");

        jLabel2.setText("Repuestos necesarios");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Cantidad:");

        jLabel5.setText("Tipo de reparación:");

        tipoReparacionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        anhadirBoton.setText("Añadir");
        anhadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirBotonActionPerformed(evt);
            }
        });

        cancelarBoton.setText("Cancelar");
        cancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBotonActionPerformed(evt);
            }
        });

        botonDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.jpg"))); // NOI18N
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });

        botonIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.jpg"))); // NOI18N
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("Es necesario cubrir todos los campos para poder registrar la reparación");

        errorCantidad.setForeground(new java.awt.Color(255, 0, 0));
        errorCantidad.setText("Cantidad vacía");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(nombreTextField)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cantidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(botonDerecha)
                                                    .addComponent(botonIzquierda))
                                                .addGap(30, 30, 30))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(errorCantidad))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipoReparacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anhadirBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelarBoton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cantidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDerecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonIzquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipoReparacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anhadirBoton)
                    .addComponent(cancelarBoton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anhadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirBotonActionPerformed
        if(tipoReparacionComboBox.getSelectedIndex() == -1 ) 
            errorLabel.setVisible(true);
        else {
            ModeloListaStrings ma= (ModeloListaStrings) lstRepuestosReparacion.getModel();
            if (ma.getElementos() == null) 
                errorLabel.setVisible(true);
            else {
                List<Repuesto> repuestos = new ArrayList<Repuesto>();
                List<Integer> cantidades = new ArrayList<Integer>();
                for (int i=0; i<ma.getSize(); i++) {
                    Integer idRepuesto = ma.getIdAt(i);
                    Repuesto repuesto = fa.obtenerRepuesto(idRepuesto);
                    repuestos.add(repuesto);
                    cantidades.add(ma.getCantidadAt(i));
                }
                try {
                    fa.anhadirReparacion(this.vehiculo, tipoReparacionComboBox.getSelectedItem().toString(), repuestos, cantidades);
                } catch (SQLException ex) {
                    Logger.getLogger(VNuevaReparacion.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
                errorLabel.setVisible(false);
                this.dispose();
            }
        }
    }//GEN-LAST:event_anhadirBotonActionPerformed

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        ModeloListaStrings mRC;
     ModeloListaStrings mC;

     mRC = (ModeloListaStrings) lstRestoRepuestos.getModel();
     mC = (ModeloListaStrings) lstRepuestosReparacion.getModel();
     mRC.nuevoElemento(mC.getElementAt(lstRepuestosReparacion.getSelectedIndex()));
     mRC.nuevoId(mC.getIdAt(lstRepuestosReparacion.getSelectedIndex()));
     mRC.nuevaCantidad(mC.getCantidadAt(lstRepuestosReparacion.getSelectedIndex()));
     mC.borrarElemento(lstRepuestosReparacion.getSelectedIndex());
             
     if (mC.getSize()==0) botonIzquierda.setEnabled(false);
     else {
         lstRepuestosReparacion.setSelectedIndex(0);
         nombreTextField.setText(lstRestoRepuestos.getSelectedValue());
     }
     lstRestoRepuestos.setSelectedIndex(mRC.getSize()-1);
     botonDerecha.setEnabled(true);
    }//GEN-LAST:event_botonIzquierdaActionPerformed

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
    ModeloListaStrings mRC;
    ModeloListaStrings mC;

    mRC = (ModeloListaStrings) lstRestoRepuestos.getModel();
    mC = (ModeloListaStrings) lstRepuestosReparacion.getModel();
    if (esNumeroValido(cantidadTextField.getText())) {
        mC.nuevoElemento(mRC.getElementAt(lstRestoRepuestos.getSelectedIndex()));
        mC.nuevoId(mRC.getIdAt(lstRestoRepuestos.getSelectedIndex()));
        mC.nuevaCantidad(Integer.parseInt(cantidadTextField.getText()));
        mRC.borrarElemento(lstRestoRepuestos.getSelectedIndex());
        if (mRC.getSize()==0) botonDerecha.setEnabled(false);
        else {
            lstRestoRepuestos.setSelectedIndex(0);
            nombreTextField.setText(lstRestoRepuestos.getSelectedValue());
        }
        lstRepuestosReparacion.setSelectedIndex(mC.getSize()-1);
        botonIzquierda.setEnabled(true);
        errorCantidad.setVisible(false);
     } else errorCantidad.setVisible(true);
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void cancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBotonActionPerformed

    private void lstRestoRepuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstRestoRepuestosMouseClicked
        ModeloListaStrings m;
        m = (ModeloListaStrings) lstRestoRepuestos.getModel();
        if (m.getSize()>0) {
            String st = m.getElementAt(lstRestoRepuestos.getSelectedIndex());
            nombreTextField.setText(st);
            cantidadTextField.setText("");
        }
    }//GEN-LAST:event_lstRestoRepuestosMouseClicked

    private void lstRepuestosReparacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstRepuestosReparacionMouseClicked
        ModeloListaStrings m;
        m = (ModeloListaStrings) lstRepuestosReparacion.getModel();
        if (m.getSize()>0) botonIzquierda.setEnabled(true);
        else botonIzquierda.setEnabled(false);
    }//GEN-LAST:event_lstRepuestosReparacionMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anhadirBoton;
    private javax.swing.JButton botonDerecha;
    private javax.swing.JButton botonIzquierda;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JTextField cantidadTextField;
    private javax.swing.JLabel errorCantidad;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstRepuestosReparacion;
    private javax.swing.JList<String> lstRestoRepuestos;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JComboBox<String> tipoReparacionComboBox;
    // End of variables declaration//GEN-END:variables

    private boolean esNumeroValido(String texto) {
        if (texto.isBlank() || texto == null) return false;
        else return texto.matches("[1-9]\\d*");
    }
    private void generarListas() {
        ArrayList<String> repuestos = new ArrayList<String>();
        ArrayList<Integer> ids = new ArrayList<Integer>();
        ArrayList<Integer> cantidades = new ArrayList<Integer>();
        for (Repuesto r : fa.getTotalRepuestos()){
            repuestos.add(r.getNombre());
            ids.add(r.getId());
            cantidades.add(0);
        }
        ModeloListaStrings ms = ((ModeloListaStrings) lstRestoRepuestos.getModel());
        ms.setElementos(repuestos, ids, cantidades);
        if (ms.getSize()>0) {
            lstRestoRepuestos.setSelectedIndex(0);
            botonDerecha.setEnabled(true);
        } else botonDerecha.setEnabled(false);
    }
    private void setBotones() {
        botonIzquierda.setEnabled(false);
        errorLabel.setVisible(false);
        errorCantidad.setVisible(false);
        nombreTextField.setEditable(false);
    }
    private void setComboBox() {
        tipoReparacionComboBox.removeAllItems();
        for (TipoReparacion r : fa.obtenerTipoReparaciones())
            tipoReparacionComboBox.addItem(r.getNombre());
        tipoReparacionComboBox.setSelectedIndex(-1);
    }

}
