/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.JefeTaller;
import aplicacion.Mecanico;
import aplicacion.Subordinado;

/**
 *
 * @author alumnogreibd
 */
public class VNuevoMecanico extends javax.swing.JDialog {

    private aplicacion.FachadaAplicacion fa;
    private VEmpleados padre;
    private boolean edicion;
    private Mecanico mEditar;
    
    /**
     * Creates new form VNuevoCliente
     */
    public VNuevoMecanico(VEmpleados parent, boolean modal, FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        setLocationRelativeTo(null);
        this.padre = parent;
        this.edicion = false;
        this.mEditar = null;
        comprobarModo();
    }
    
    public VNuevoMecanico(VEmpleados parent, boolean modal, FachadaAplicacion fa, Mecanico m) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        setLocationRelativeTo(null);
        this.padre = parent;
        this.edicion = true;
        this.mEditar = m;
        comprobarModo();
    }
    
    private void comprobarModo(){
        if(edicion){
            botonAnhadir.setText("Editar");
            anhadirId.setText(mEditar.getIdMecanico());
            anhadirId.setEditable(false);
            anhadirNombre.setText(mEditar.getNombre());
            anhadirClave.setText(mEditar.getClave());
            anhadirTlf.setText(mEditar.getTelefonoContacto());
            anhadirSueldo.setText(String.valueOf(mEditar.getSueldoBase()));
            botonAscender.setVisible(true);
            textoTipo.setVisible(false);
            comboTipo.setVisible(false);
            estadoBotonAscender();
        }
        else{
            botonAnhadir.setText("Añadir");
            anhadirId.setText("");
            anhadirId.setEditable(true);
            anhadirNombre.setText("");
            anhadirClave.setText("");
            anhadirTlf.setText("");
            anhadirSueldo.setText("");
            botonAscender.setVisible(false);
            textoTipo.setVisible(true);
            comboTipo.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        anhadirId = new javax.swing.JTextField();
        anhadirTlf = new javax.swing.JTextField();
        anhadirNombre = new javax.swing.JTextField();
        botonAnhadir = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        anhadirSueldo = new javax.swing.JTextField();
        textoTipo = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        anhadirClave = new javax.swing.JTextField();
        botonAscender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Cliente");

        jLabel1.setText("Id:");

        jLabel2.setText("Teléfono de contacto:");

        jLabel3.setText("Nombre:");

        anhadirNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirNombreActionPerformed(evt);
            }
        });

        botonAnhadir.setText("Añadir");
        botonAnhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnhadirActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Sueldo base:");

        textoTipo.setText("Tipo:");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe de taller", "Subordinado" }));

        jLabel6.setText("Clave:");

        botonAscender.setText("Ascender");
        botonAscender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAscenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anhadirTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoTipo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(anhadirId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(anhadirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(botonAnhadir)
                                .addGap(18, 18, 18)
                                .addComponent(botonAscender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonCancelar)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anhadirClave, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anhadirSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(anhadirId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(anhadirTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(anhadirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(anhadirSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTipo)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(anhadirClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnhadir)
                    .addComponent(botonCancelar)
                    .addComponent(botonAscender))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anhadirNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anhadirNombreActionPerformed

    private void botonAnhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnhadirActionPerformed
        if(this.edicion){
            updateMecanico();
        }else{
            anhadirMecanico(); 
        }
        this.dispose();
    }//GEN-LAST:event_botonAnhadirActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAscenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAscenderActionPerformed
        // TODO add your handling code here:
        fa.ascenderMecanico(mEditar.getIdMecanico());
        this.dispose();
    }//GEN-LAST:event_botonAscenderActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anhadirClave;
    private javax.swing.JTextField anhadirId;
    private javax.swing.JTextField anhadirNombre;
    private javax.swing.JTextField anhadirSueldo;
    private javax.swing.JTextField anhadirTlf;
    private javax.swing.JButton botonAnhadir;
    private javax.swing.JButton botonAscender;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel textoTipo;
    // End of variables declaration//GEN-END:variables

    public void anhadirMecanico(){
        String id = anhadirId.getText().trim();
        String nombre = anhadirNombre.getText().trim();
        String clave = anhadirClave.getText().trim();
        String tlf = anhadirTlf.getText().trim();
        String s = anhadirSueldo.getText().trim();
        String tipo = (String) comboTipo.getSelectedItem();
        Integer sueldo = 0;
        if(!s.isEmpty()) sueldo = Integer.parseInt(s);
        if(id.isEmpty() || nombre.isEmpty() || clave.isEmpty() || tlf.isEmpty()){
            VAviso va = new VAviso(this.padre.getParent(), true, "Alguno de los campos obligatorios es vacío");
            va.setVisible(true);
        }
        else{
            switch (tipo){
                case "Jefe de taller": fa.anhadirJefeDeTaller(id,nombre,clave,tlf,sueldo); break;
                case "Subordinado": fa.anhadirSubordinado(id,nombre,clave,tlf,sueldo); break;
            }
        }
    }
    
    public void updateMecanico(){
        String id = mEditar.getIdMecanico();
        String nombre = anhadirNombre.getText().trim();
        String clave = anhadirClave.getText().trim();
        String tlf = anhadirTlf.getText().trim();
        String s = anhadirSueldo.getText().trim();
        Integer sueldo = 0;
        if(!s.isEmpty()) sueldo = Integer.parseInt(s);
        if(id.isEmpty() || nombre.isEmpty() || clave.isEmpty() || tlf.isEmpty()){
            VAviso va = new VAviso(this.padre.getParent(), true, "Alguno de los campos obligatorios es vacío");
            va.setVisible(true);
        }
        else{
            if(!fa.updateMecanico(id, nombre, clave, tlf, sueldo)){
                VAviso va = new VAviso(this.padre.getParent(), true, "El subordinado está participando en una reparación y no puede ser ascendido todavía");
                va.setVisible(true);
            }
        }
    }
    
    public void estadoBotonAscender(){
        if(this.mEditar instanceof Subordinado){
            botonAscender.setEnabled(true);
        }
        else{
            botonAscender.setEnabled(false);
        }
    }
}
