/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VPrincipal.java
 *
 * Created on 27-ene-2011, 10:31:24
 */

package gui;

import aplicacion.JefeTaller;
import aplicacion.Mecanico;
import aplicacion.Vehiculo;


/**
 *
 * @author basesdatos
 */
public class VPrincipal extends javax.swing.JFrame {
  
    aplicacion.FachadaAplicacion fa;
    Vehiculo vehiculoseleccionado;
    Mecanico mecanicoEnAcceso;
    
    /** Creates new form VPrincipal */
    public VPrincipal(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
        setLocationRelativeTo(null);
        modificarVehiculoBoton.setEnabled(false);
        eliminarVehiculoBoton.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscaMatricula = new javax.swing.JTextField();
        etiquetaTitulo = new javax.swing.JLabel();
        buscaMarca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscaModelo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscaCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buscaCombustible = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscaSupervisor = new javax.swing.JTextField();
        anhadirVehiculoBoton = new javax.swing.JButton();
        modificarVehiculoBoton = new javax.swing.JButton();
        eliminarVehiculoBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        pestanhaGestion = new javax.swing.JMenu();
        menuEmpleados = new javax.swing.JMenuItem();
        menuSolicitudes = new javax.swing.JMenuItem();
        pestanhaPrincipal = new javax.swing.JMenu();
        menuPersonal = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca de Informática");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        buscaMatricula.setToolTipText("Titulo a buscar");

        etiquetaTitulo.setText("Matrícula:");

        jLabel1.setText("Marca:");

        jLabel2.setText("Modelo:");

        tablaVehiculos.setModel(new gui.ModeloTablaVehiculos());
        tablaVehiculos.setColumnSelectionAllowed(true);
        tablaVehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaVehiculos.getTableHeader().setReorderingAllowed(false);
        tablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);
        tablaVehiculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente:");

        jLabel4.setText("Combustible:");

        jLabel5.setText("Supervisor:");

        anhadirVehiculoBoton.setText("Añadir");
        anhadirVehiculoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirVehiculoBotonActionPerformed(evt);
            }
        });

        modificarVehiculoBoton.setText("Modificar");
        modificarVehiculoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarVehiculoBotonActionPerformed(evt);
            }
        });

        eliminarVehiculoBoton.setText("Eliminar");
        eliminarVehiculoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVehiculoBotonActionPerformed(evt);
            }
        });

        pestanhaGestion.setText("Gestión");

        menuEmpleados.setText("Empleados");
        menuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadosActionPerformed(evt);
            }
        });
        pestanhaGestion.add(menuEmpleados);

        menuSolicitudes.setText("Solicitudes");
        menuSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSolicitudesActionPerformed(evt);
            }
        });
        pestanhaGestion.add(menuSolicitudes);

        jMenuBar1.add(pestanhaGestion);

        pestanhaPrincipal.setText("Principal");

        menuPersonal.setText("Personal");
        menuPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPersonalActionPerformed(evt);
            }
        });
        pestanhaPrincipal.add(menuPersonal);

        menuStock.setText("Stock");
        pestanhaPrincipal.add(menuStock);

        jMenuBar1.add(pestanhaPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscaSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(anhadirVehiculoBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarVehiculoBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarVehiculoBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTitulo)
                    .addComponent(jLabel2)
                    .addComponent(buscaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(buscaCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buscaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buscaSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnBuscar)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(anhadirVehiculoBoton)
                    .addComponent(modificarVehiculoBoton)
                    .addComponent(eliminarVehiculoBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Biblioteca Informática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarVehiculos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void menuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadosActionPerformed
        VEmpleados ve = new VEmpleados(this, true, this.fa);
        ve.setVisible(true);
    }//GEN-LAST:event_menuEmpleadosActionPerformed

    private void menuSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSolicitudesActionPerformed
        // TODO add your handling code here:
        VCategorias vc = new VCategorias(this, true, this.fa);
        vc.setVisible(true);
    }//GEN-LAST:event_menuSolicitudesActionPerformed

    private void anhadirVehiculoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirVehiculoBotonActionPerformed
        // TODO add your handling code here:
        VVehiculo vnv= new VVehiculo(this, true, this.fa);
        vnv.setVisible(true);
        modificarVehiculoBoton.setEnabled(false);
        buscarVehiculos();

    }//GEN-LAST:event_anhadirVehiculoBotonActionPerformed

    private void modificarVehiculoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarVehiculoBotonActionPerformed

        VVehiculo vv= new VVehiculo(this, true, this.fa, vehiculoseleccionado.getMatricula());
        vv.setVisible(true);
        modificarVehiculoBoton.setEnabled(false);
        setBotonesBlanco();
        buscarVehiculos();
    }//GEN-LAST:event_modificarVehiculoBotonActionPerformed

    private void eliminarVehiculoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVehiculoBotonActionPerformed

            if(vehiculoseleccionado!=null)
                fa.eliminarVehiculo(vehiculoseleccionado.getMatricula());
            setBotonesBlanco();
            buscarVehiculos();
            modificarVehiculoBoton.setEnabled(false);
            eliminarVehiculoBoton.setEnabled(false);
    }//GEN-LAST:event_eliminarVehiculoBotonActionPerformed

    private void tablaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVehiculosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada= tablaVehiculos.getSelectedRow();
        ModeloTablaVehiculos mtl = (ModeloTablaVehiculos) tablaVehiculos.getModel();
        
        vehiculoseleccionado = mtl.obtenerVehiculo(filaSeleccionada);
        
        setBotonesVehiculo(vehiculoseleccionado);
        modificarVehiculoBoton.setEnabled(true);
        if (fa.vehiculoTieneReparacionesPendientes(vehiculoseleccionado)) eliminarVehiculoBoton.setEnabled(false);
        else eliminarVehiculoBoton.setEnabled(true);
    }//GEN-LAST:event_tablaVehiculosMouseClicked

    private void menuPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPersonalActionPerformed
        VPersonal vp = new VPersonal(this, true, this.fa, this.mecanicoEnAcceso);
        vp.setVisible(true);
        vp.obtenerDatosMecanicoActual(); 
    }//GEN-LAST:event_menuPersonalActionPerformed


    private void setBotonesVehiculo(Vehiculo vehiculo){
        buscaMatricula.setText(vehiculo.getMatricula());
        buscaCliente.setText(vehiculo.getPropietarioDNI());   
        buscaModelo.setText(vehiculo.getModelo());
        if(vehiculo.getSupervisorID()!=null) {
            JefeTaller j = fa.obtenerJefeTaller(vehiculo.getSupervisorID());
            buscaSupervisor.setText(j.getIdMecanico());
        } else buscaSupervisor.setText("");
        buscaCombustible.setText(vehiculo.getCombustible());
        buscaMarca.setText(vehiculo.getMarca());
        
        modificarVehiculoBoton.setEnabled(true);
    }
    
    private void setBotonesBlanco( ){
        buscaMatricula.setText("");
        buscaCliente.setText(""); 
        buscaModelo.setText("");
        buscaSupervisor.setText("");
        buscaCombustible.setText("");
        buscaMarca.setText("");
        modificarVehiculoBoton.setEnabled(false);
    }
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anhadirVehiculoBoton;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField buscaCliente;
    private javax.swing.JTextField buscaCombustible;
    private javax.swing.JTextField buscaMarca;
    private javax.swing.JTextField buscaMatricula;
    private javax.swing.JTextField buscaModelo;
    private javax.swing.JTextField buscaSupervisor;
    private javax.swing.JButton eliminarVehiculoBoton;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuEmpleados;
    private javax.swing.JMenuItem menuPersonal;
    private javax.swing.JMenuItem menuSolicitudes;
    private javax.swing.JMenuItem menuStock;
    private javax.swing.JButton modificarVehiculoBoton;
    private javax.swing.JMenu pestanhaGestion;
    private javax.swing.JMenu pestanhaPrincipal;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables

    public void comprobarMecanico(Mecanico m){
        mecanicoEnAcceso = m;
        if(m instanceof JefeTaller){
            pestanhaGestion.setEnabled(true);
        } else{
            pestanhaGestion.setEnabled(false);
        }
    }
    
    public void buscarVehiculos(){
        ModeloTablaVehiculos m;

        m=(ModeloTablaVehiculos) tablaVehiculos.getModel();
        m.setFilas(fa.obtenerVehiculos(buscaMatricula.getText(), buscaCliente.getText(), buscaMarca.getText(), buscaModelo.getText(), buscaSupervisor.getText(), buscaCombustible.getText()));
        if (m.getRowCount() > 0) {
            tablaVehiculos.setRowSelectionInterval(0, 0);
            tablaVehiculos.requestFocus();
            
            Vehiculo vehiculo= m.obtenerVehiculo(0);
            setBotonesVehiculo(vehiculo);
        }else setBotonesBlanco();
    }
    
    public Mecanico getMecanicoApp() { return mecanicoEnAcceso; }
}
