/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.JefeTaller;
import aplicacion.Reparacion;
import aplicacion.Stock_U_A;
import aplicacion.TipoReparacion;
import java.util.List;

/**
 *
 * @author alumnogreibd
 */
public class VReparacion extends javax.swing.JDialog {

    private Reparacion reparacion;
    private TipoReparacion tipoReparacion;
    private JefeTaller supervisor;
    
    private VVehiculo padre;
    private aplicacion.FachadaAplicacion fa;
    
    public VReparacion(VVehiculo parent, boolean modal, FachadaAplicacion fa, Integer idreparacion) {
        super(parent, modal);
        this.padre = parent;
        this.fa = fa;
        this.reparacion=fa.obtenerReparacion(idreparacion);
        this.tipoReparacion=fa.obtenerTipoReparacion(reparacion.getTipo());
        if(reparacion.getSupervisorid()!=null) this.supervisor=fa.obtenerJefeTaller(reparacion.getSupervisorid());
        initComponents();
        setTextos();
        setBotones();
        buscarStock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        repararBoton = new javax.swing.JButton();
        descartarBoton = new javax.swing.JButton();
        anhadirEmpleadoBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTipoReparacionTextArea = new javax.swing.JTextArea();
        fechaInicioTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        tipoReparacionTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaFinTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        supervisorNombreTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        supervisorIdTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Vehículo");

        jLabel1.setText("Id reparación:");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Fecha inicio:");

        jLabel4.setText("Descripción:");

        jLabel5.setText("Repuestos necesarios:");

        tablaStock.setModel(new gui.ModeloTablaStock_U_A());
        jScrollPane1.setViewportView(tablaStock);

        repararBoton.setText("Reparar");
        repararBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repararBotonActionPerformed(evt);
            }
        });

        descartarBoton.setText("Descartar");
        descartarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBotonActionPerformed(evt);
            }
        });

        anhadirEmpleadoBoton.setText("Añadir empleado\n en prácticas");
        anhadirEmpleadoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirEmpleadoBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        descripcionTipoReparacionTextArea.setEditable(false);
        descripcionTipoReparacionTextArea.setColumns(20);
        descripcionTipoReparacionTextArea.setLineWrap(true);
        descripcionTipoReparacionTextArea.setRows(5);
        jScrollPane2.setViewportView(descripcionTipoReparacionTextArea);

        fechaInicioTextField.setEditable(false);

        idTextField.setEditable(false);

        tipoReparacionTextField.setEditable(false);

        jLabel6.setText("Fecha fin:");

        fechaFinTextField.setEditable(false);

        jLabel7.setText("Supervisor:");

        supervisorNombreTextField.setEditable(false);

        jLabel8.setText("Id supervisor:");

        supervisorIdTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoReparacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(supervisorNombreTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(anhadirEmpleadoBoton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(supervisorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaFinTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(fechaInicioTextField)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(repararBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descartarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirBoton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(fechaInicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipoReparacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(fechaFinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supervisorNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(supervisorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(anhadirEmpleadoBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repararBoton)
                    .addComponent(descartarBoton)
                    .addComponent(salirBoton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repararBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repararBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repararBotonActionPerformed

    private void anhadirEmpleadoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirEmpleadoBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anhadirEmpleadoBotonActionPerformed

    private void descartarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBotonActionPerformed
        fa.borrarReparacion(reparacion.getIdreparacion());
    }//GEN-LAST:event_descartarBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirBotonActionPerformed

    private void setTextos() {
        idTextField.setText(String.valueOf(reparacion.getIdreparacion()));
        fechaInicioTextField.setText(reparacion.getFecha_inicio());
        if(reparacion.getFecha_fin()==null)fechaFinTextField.setText("  -");
        else fechaFinTextField.setText(reparacion.getFecha_fin());
        tipoReparacionTextField.setText(reparacion.getTipo());
        descripcionTipoReparacionTextArea.setText(tipoReparacion.getDescripcion());
        if(supervisor!=null) {
            supervisorNombreTextField.setText(supervisor.getNombre());
            supervisorIdTextField.setText(supervisor.getIdMecanico());
        } else {
            supervisorNombreTextField.setText("  -");
            supervisorIdTextField.setText("  -");
        }
    }
    
    private void setBotones() {
        if(!tipoReparacion.esApto_practicas())anhadirEmpleadoBoton.setEnabled(false);
        if(reparacion.getFecha_fin()!=null) descartarBoton.setEnabled(false);
    }
    
    private void buscarStock() {
        ModeloTablaStock_U_A r;
        List<Stock_U_A> ua = fa.obtenerStock_U_A(reparacion.getIdreparacion());

        r=(ModeloTablaStock_U_A) tablaStock.getModel();
        r.setFilas(ua);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anhadirEmpleadoBoton;
    private javax.swing.JButton descartarBoton;
    private javax.swing.JTextArea descripcionTipoReparacionTextArea;
    private javax.swing.JTextField fechaFinTextField;
    private javax.swing.JTextField fechaInicioTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton repararBoton;
    private javax.swing.JButton salirBoton;
    private javax.swing.JTextField supervisorIdTextField;
    private javax.swing.JTextField supervisorNombreTextField;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTextField tipoReparacionTextField;
    // End of variables declaration//GEN-END:variables
}
