/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.Solicitud;

/**
 *
 * @author alumnogreibd
 */
public class VSolicitudes extends javax.swing.JDialog {
    
    aplicacion.FachadaAplicacion fa;
    Solicitud solicitudSeleccionada;
    /**
     * Creates new form VSolicitudes
     */
    public VSolicitudes(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        setLocationRelativeTo(null);
        aceptarButton.setEnabled(false);
        denegarButton.setEnabled(false);
        buscarSolicitudes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        aceptarButton = new javax.swing.JButton();
        denegarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Solicitudes");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablaSolicitudes.setModel(new gui.ModeloTablaSolicitudes(this.fa));
        tablaSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSolicitudes);

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        denegarButton.setText("Denegar");
        denegarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denegarButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(398, 398, 398)
                                .addComponent(salirButton))
                            .addComponent(denegarButton))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(denegarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salirButton))
                    .addComponent(aceptarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        /*
        int filaSeleccionada= tablaSolicitudes.getSelectedRow();
        ModeloTablaSolicitudes mts = (ModeloTablaSolicitudes) tablaSolicitudes.getModel();
        
        solicitudSeleccionada = mts.obtenerSolicitud(filaSeleccionada);
        
        aceptarButton.setEnabled(true);
        denegarButton.setEnabled(true);
        */
        }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tablaSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSolicitudesMouseClicked
        int filaSeleccionada= tablaSolicitudes.getSelectedRow();
        ModeloTablaSolicitudes mts = (ModeloTablaSolicitudes) tablaSolicitudes.getModel();
        
        solicitudSeleccionada = mts.obtenerSolicitud(filaSeleccionada);
        
        aceptarButton.setEnabled(true);
        denegarButton.setEnabled(true);
    }//GEN-LAST:event_tablaSolicitudesMouseClicked

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        ModeloTablaSolicitudes mts = (ModeloTablaSolicitudes) tablaSolicitudes.getModel();
        
        solicitudSeleccionada = mts.obtenerSolicitud(tablaSolicitudes.getSelectedRow());
        if (solicitudSeleccionada != null) {
            fa.aumentarStockPorSolicitud(solicitudSeleccionada);
            fa.eliminarSolicitud(solicitudSeleccionada);
        }
        buscarSolicitudes();
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void denegarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denegarButtonActionPerformed
        ModeloTablaSolicitudes mts = (ModeloTablaSolicitudes) tablaSolicitudes.getModel();
        
        solicitudSeleccionada = mts.obtenerSolicitud(tablaSolicitudes.getSelectedRow());
        if (solicitudSeleccionada != null)
            fa.eliminarSolicitud(solicitudSeleccionada);
        buscarSolicitudes();
    }//GEN-LAST:event_denegarButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton denegarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salirButton;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables

    public void buscarSolicitudes(){
        ModeloTablaSolicitudes m;

        m=(ModeloTablaSolicitudes) tablaSolicitudes.getModel();
        m.setFilas(fa.obtenerSolicitudes());
        if (m.getRowCount() > 0) {
            tablaSolicitudes.setRowSelectionInterval(0, 0);
            tablaSolicitudes.requestFocus();
            denegarButton.setEnabled(true);
            aceptarButton.setEnabled(true);
           // Vehiculo vehiculo= m.obtenerVehiculo(0);
           // setBotonesVehiculo(vehiculo);
        } else  {
            denegarButton.setEnabled(false);
            aceptarButton.setEnabled(false);
        }
    }




}
