/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Mecanico;
import aplicacion.Repuesto;
import java.util.ArrayList;

/**
 *
 * @author alumnogreibd
 */
public class VStock extends javax.swing.JDialog {
    private aplicacion.FachadaAplicacion fa;
    private Mecanico mecanicoEnAcceso;
    private Repuesto repuestoSeleccionado;
    private VPrincipal padre;
    /**
     * Creates new form VStock
     */
    public VStock(VPrincipal parent, boolean modal, aplicacion.FachadaAplicacion fa, Mecanico mecanico) {
        super(parent, modal);
        this.padre=parent;
        this.fa = fa;
        this.mecanicoEnAcceso = mecanico;
        initComponents();
                setLocationRelativeTo(null);

        setBotones();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        buscarBoton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stockTextField = new javax.swing.JTextField();
        precioTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        solicitarBoton = new javax.swing.JButton();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Stock");

        tablaStock.setModel(new ModeloTablaAlmacen());
        tablaStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaStock);

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        buscarBoton.setText("Buscar");
        buscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("Stock:");

        jLabel4.setText("Precio unidad (€):");

        jLabel5.setText("Descripción:");

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        jScrollPane2.setViewportView(descripcionTextArea);

        solicitarBoton.setText("Solicitar");
        solicitarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarBotonActionPerformed(evt);
            }
        });

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarBoton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(salirBoton)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precioTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(solicitarBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarBoton))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(stockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(precioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solicitarBoton)
                    .addComponent(salirBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaStockMouseClicked
        int filaSeleccionada= tablaStock.getSelectedRow();
        ModeloTablaAlmacen mta = (ModeloTablaAlmacen) tablaStock.getModel();
        repuestoSeleccionado = mta.obtenerRepuesto(filaSeleccionada);
        rellenarTextField(repuestoSeleccionado);
        solicitarBoton.setEnabled(true);
    }//GEN-LAST:event_tablaStockMouseClicked

    private void buscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBotonActionPerformed
        buscarRepuesto();
    }//GEN-LAST:event_buscarBotonActionPerformed

    private void solicitarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarBotonActionPerformed
        VNuevaSolicitud vns = new VNuevaSolicitud(this , true, this.fa, this.mecanicoEnAcceso, this.repuestoSeleccionado);
        vns.setVisible(true);
        setTextFieldsBlanco();
        buscarRepuesto();
    }//GEN-LAST:event_solicitarBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBoton;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField precioTextField;
    private javax.swing.JButton salirBoton;
    private javax.swing.JButton solicitarBoton;
    private javax.swing.JTextField stockTextField;
    private javax.swing.JTable tablaStock;
    // End of variables declaration//GEN-END:variables
    
    private void setBotones() {
        solicitarBoton.setEnabled(false);
    }
    
    private void rellenarTextField(Repuesto r) {
        idTextField.setText(r.getId().toString());
        nombreTextField.setText(r.getNombre());
        stockTextField.setText(r.getStock().toString());
        precioTextField.setText(r.getPreciounidad().toString());
        descripcionTextArea.setText(r.getDescripcion());
    }

    private void setTextFieldsBlanco() {
        idTextField.setText("");
        nombreTextField.setText("");
        stockTextField.setText("");
        precioTextField.setText("");
        descripcionTextArea.setText("");
    }
    
    private void inicializarTabla() {
        ModeloTablaAlmacen mta = ((ModeloTablaAlmacen) tablaStock.getModel());
        mta.setFilas(fa.getTotalRepuestos());
    }
    
    private boolean esNumeroValido(String texto) {
        if (texto.isBlank() || texto == null) return false;
        else return texto.matches("[1-9]\\d*");
    }
    
    private void buscarRepuesto() {
        ModeloTablaAlmacen m=(ModeloTablaAlmacen) tablaStock.getModel();
        if (nombreTextField.getText().isBlank() && !esNumeroValido(idTextField.getText())) m.setFilas(fa.getTotalRepuestos());
        else if (nombreTextField.getText().isBlank() && esNumeroValido(idTextField.getText())) {
            ArrayList<Repuesto> repuestos = new ArrayList<Repuesto>();
            repuestos.add(fa.obtenerRepuesto(Integer.parseInt(idTextField.getText())));
            m.setFilas(repuestos);
        }
        else m.setFilas(fa.obtenerRepuestos(idTextField.getText(), nombreTextField.getText()));
        if (m.getRowCount() > 0) {
            tablaStock.setRowSelectionInterval(0, 0);
            tablaStock.requestFocus();
        }
        setTextFieldsBlanco();
    }
}
