/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alumnogreibd
 */
public class VUsuarios extends javax.swing.JDialog {
    private aplicacion.FachadaAplicacion fa;
    private VPrincipal padre;
    
    /**
     * Creates new form VUsuarios
     */
    public VUsuarios(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        this.padre = (VPrincipal) parent;
        initComponents();
        setLocationRelativeTo(null);
        buscarUsuarios("","");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        BuscaNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BuscaId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ModificaId = new javax.swing.JTextField();
        ModificaClave = new javax.swing.JTextField();
        ModificaNombre = new javax.swing.JTextField();
        ModificaEmail = new javax.swing.JTextField();
        ModificaDireccion = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        ModificaTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        BuscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Id:");

        tablaUsuarios.setModel(new ModeloTablaUsuarios());
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jLabel3.setText("Id:");

        jLabel4.setText("Clave:");

        jLabel5.setText("Tipo:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Email:");

        jLabel8.setText("Direccion:");

        ModificaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaIdActionPerformed(evt);
            }
        });

        ModificaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaEmailActionPerformed(evt);
            }
        });

        ModificaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaDireccionActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        ModificaTipo.setModel(new DefaultComboBoxModel(aplicacion.TipoUsuario.values()));
        ModificaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscaId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BuscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModificaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(ModificaId))
                        .addGap(12, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ModificaClave, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ModificaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModificaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModificaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(BuscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(BuscaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(ModificaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(ModificaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnBorrar)
                    .addComponent(btnSalir))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaNombreActionPerformed

    private void ModificaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaIdActionPerformed

    private void ModificaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaDireccionActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        ModificaClave.setText("");
        ModificaId.setText("");
        ModificaNombre.setText("");
        ModificaEmail.setText("");
        ModificaDireccion.setText("");
        ModificaTipo.setSelectedItem("Normal");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(ModificaId.getText().isBlank() || ModificaNombre.getText().isBlank()){
            VAviso va = new VAviso(this.padre, true, "El campo id o nombre no pueden estar vacíos");
            va.setVisible(true);
        }
        else if(existeUsuario(ModificaId.getText())){
            editarUsuario(ModificaId.getText(), ModificaClave.getText(), ModificaNombre.getText(), ModificaDireccion.getText(), ModificaEmail.getText(), ModificaTipo.getSelectedItem().toString());
        } else{
            crearUsuario(ModificaId.getText(), ModificaClave.getText(), ModificaNombre.getText(), ModificaDireccion.getText(), ModificaEmail.getText(), ModificaTipo.getSelectedItem().toString());
        }
        buscarUsuarios("","");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ModificaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaEmailActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarUsuarios(BuscaId.getText(), BuscaNombre.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void ModificaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificaTipoActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        obtenerUsuarioSeleccionado();
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if(tablaUsuarios.getSelectedRow()!=-1){ //VER PRESTAMOS
            ModeloTablaUsuarios m;
            m=(ModeloTablaUsuarios) tablaUsuarios.getModel();
            borrarUsuario(m.obtenerUsuario(tablaUsuarios.getSelectedRow()).getIdUsuario());
            buscarUsuarios("","");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscaId;
    private javax.swing.JTextField BuscaNombre;
    private javax.swing.JTextField ModificaClave;
    private javax.swing.JTextField ModificaDireccion;
    private javax.swing.JTextField ModificaEmail;
    private javax.swing.JTextField ModificaId;
    private javax.swing.JTextField ModificaNombre;
    private javax.swing.JComboBox<String> ModificaTipo;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables


    public void buscarUsuarios(String id, String nombre){
        ModeloTablaUsuarios m;

        m=(ModeloTablaUsuarios) tablaUsuarios.getModel();
        m.setFilas(fa.obtenerUsuarios(id, nombre));
        if (m.getRowCount() > 0) {
            tablaUsuarios.setRowSelectionInterval(0, 0);
            obtenerUsuarioSeleccionado();
            btnBorrar.setEnabled(true);
        }
        else{
            btnBorrar.setEnabled(false);
            ModificaClave.setText("");
            ModificaId.setText("");
            ModificaNombre.setText("");
            ModificaEmail.setText("");
            ModificaDireccion.setText("");
            ModificaTipo.setSelectedItem("Normal");
        }
    }
    
    public void obtenerUsuarioSeleccionado(){
        if(tablaUsuarios.getSelectedRow()!=-1){
            ModeloTablaUsuarios m;
            m=(ModeloTablaUsuarios) tablaUsuarios.getModel();
            filaSeleccionada(m.obtenerUsuario(tablaUsuarios.getSelectedRow()));
        }
    }
    
    public void filaSeleccionada(aplicacion.Mecanico u){
        ModificaNombre.setText(u.getNombre());
        ModificaClave.setText(u.getClave());
        ModificaEmail.setText(u.getEmail());
        ModificaDireccion.setText(u.getDireccion());
        ModificaId.setText(u.getIdUsuario());
        ModificaTipo.setSelectedItem(u.getTipoUsuario());
    }
    
    public boolean existeUsuario(String id){
        return fa.existeUsuario(id);
    }
    
    public void editarUsuario(String id, String clave, String nombre, String direccion, String email, String tipo){
        fa.editarUsuario(id, clave, nombre, direccion, email, tipo);
    }
    
    public void crearUsuario(String id, String clave, String nombre, String direccion, String email, String tipo){
        fa.crearUsuario(id, clave, nombre, direccion, email, tipo);
    }
    
    public void borrarUsuario(String id){
        fa.borrarUsuario(id);
    }
}
