/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VLibro.java
 *
 * Created on 16-feb-2011, 18:17:07
 */

package gui;

import aplicacion.Cliente;
import aplicacion.Vehiculo;
import aplicacion.Mecanico;
import aplicacion.Reparacion;
import java.util.List;



/**
 *
 * @author basesdatos
 */
public class VVehiculo extends javax.swing.JDialog {

     private Vehiculo vehiculo;
     private Cliente propietario;
     private Mecanico supervisor;
     private Cliente clienteseleccionado;

     private final VPrincipal padre;
     private final aplicacion.FachadaAplicacion fa;

    //PARA MODIFICAR VEHICULO
    public VVehiculo(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, String matricula) {
        super(parent, modal);
        this.fa=fa;
        this.vehiculo=fa.obtenerVehiculo(matricula);
        this.propietario=fa.obtenerCliente(vehiculo.getPropietarioDNI());
        if(vehiculo.getSupervisorID()!=null) this.supervisor=fa.obtenerJefeTaller(vehiculo.getSupervisorID());
        
        initComponents();
        setLocationRelativeTo(null);
        padre=(VPrincipal) parent;
        
        setBotonesVehiculo(vehiculo);
        buscarClientes();
        buscarReparaciones();
        eliminarClienteBoton.setEnabled(false);
    }
    
    //PARA NUEVO VEHÍCULO
    public VVehiculo(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        
        initComponents();
        setLocationRelativeTo(null);
        padre=(VPrincipal) parent;
        panelVehiculo.setEnabled(false);
        
        buscarClientes();
        for(String s : fa.obtenerIDsJefesTaller())
        seleccionSupervisor.addItem(s); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVehiculo = new javax.swing.JTabbedPane();
        panelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscaMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscaMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buscaModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscaCombustible = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnActualizarVehiculo = new javax.swing.JButton();
        buscaKilometraje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        seleccionSupervisor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        buscaCliente = new javax.swing.JTextField();
        seleccionarClienteBoton = new javax.swing.JButton();
        anadirClienteBoton = new javax.swing.JButton();
        eliminarClienteBoton = new javax.swing.JButton();
        panelReparaciones = new javax.swing.JPanel();
        tablaReparaciones = new javax.swing.JScrollPane();
        TablaReparaciones = new javax.swing.JTable();
        gestionarBoton = new javax.swing.JButton();
        anhadirBoton = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Vehículo");
        setResizable(false);

        jLabel2.setText("Matrícula:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Modelo:");

        jLabel5.setText("Combustible:");

        jLabel7.setText("Kilometraje:");

        btnActualizarVehiculo.setText("Actualizar");
        btnActualizarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVehiculoActionPerformed(evt);
            }
        });

        jLabel1.setText("Supervisor:");

        jLabel6.setText("Cliente:");

        tablaClientes.setModel(new ModeloTablaClientes());
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        buscaCliente.setEditable(false);

        seleccionarClienteBoton.setText("Seleccionar Cliente");
        seleccionarClienteBoton.setDefaultCapable(false);
        seleccionarClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarClienteBotonActionPerformed(evt);
            }
        });

        anadirClienteBoton.setText("Añadir Cliente");
        anadirClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirClienteBotonActionPerformed(evt);
            }
        });

        eliminarClienteBoton.setText("Eliminar Cliente");
        eliminarClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClienteBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))))
                        .addGap(36, 36, 36)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscaMatricula)
                            .addComponent(buscaMarca)
                            .addComponent(buscaKilometraje, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(buscaCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seleccionSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buscaCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buscaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(anadirClienteBoton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(seleccionarClienteBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarClienteBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizarVehiculo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buscaCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buscaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(buscaKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(seleccionSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(buscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anadirClienteBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionarClienteBoton)
                    .addComponent(btnActualizarVehiculo)
                    .addComponent(eliminarClienteBoton))
                .addGap(15, 15, 15))
        );

        panelVehiculo.addTab("Vehiculo", panelDatos);

        TablaReparaciones.setModel(new ModeloTablaReparaciones(this.fa));
        TablaReparaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaReparacionesMouseClicked(evt);
            }
        });
        tablaReparaciones.setViewportView(TablaReparaciones);

        gestionarBoton.setText("Gestionar");
        gestionarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionarBotonActionPerformed(evt);
            }
        });

        anhadirBoton.setText("Añadir");
        anhadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReparacionesLayout = new javax.swing.GroupLayout(panelReparaciones);
        panelReparaciones.setLayout(panelReparacionesLayout);
        panelReparacionesLayout.setHorizontalGroup(
            panelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReparacionesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReparacionesLayout.createSequentialGroup()
                        .addComponent(gestionarBoton)
                        .addGap(26, 26, 26)
                        .addComponent(anhadirBoton))
                    .addComponent(tablaReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelReparacionesLayout.setVerticalGroup(
            panelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReparacionesLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(tablaReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gestionarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anhadirBoton)))
        );

        panelVehiculo.addTab("Reparaciones", panelReparaciones);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelVehiculo.getAccessibleContext().setAccessibleName("Libro");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setBotonesVehiculo(Vehiculo vehiculo){
        buscaMatricula.setText(vehiculo.getMatricula());
        buscaMatricula.setEditable(false);
        buscaModelo.setText(vehiculo.getModelo());
        buscaCombustible.setText(vehiculo.getCombustible());
        buscaMarca.setText(vehiculo.getMarca());
        buscaKilometraje.setText(vehiculo.getKilometraje().toString());
        buscaCliente.setText(this.propietario.getNombre());
        
        seleccionSupervisor.setSelectedItem(vehiculo.getSupervisorID());
        for(String s : fa.obtenerIDsJefesTaller())
        seleccionSupervisor.addItem(s);
        
        gestionarBoton.setEnabled(false);
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVehiculoActionPerformed
        if(clienteseleccionado!=null) this.propietario=clienteseleccionado;
        if(seleccionSupervisor.getSelectedItem() != null)
            this.supervisor=fa.obtenerJefeTaller(seleccionSupervisor.getSelectedItem().toString());
        else this.supervisor = null;
        
        if(this.vehiculo!=null){
            
            LOCAL_actualizarVehiculo();   //no asegura que no se violen las claves foráneas ni controla lo que pase después            
            fa.actualizarVehiculo(this.vehiculo);
            
        } else{
            int kilometraje=0;
            if(!buscaKilometraje.getText().isBlank())
                kilometraje = Integer.parseInt(buscaKilometraje.getText());
            
            if(propietario!=null)
                if(!(buscaMatricula.getText().isBlank() || buscaMarca.getText().isBlank() || buscaModelo.getText().isBlank() || buscaCombustible.getText().isBlank() || propietario.getDni().isBlank())) {
                    Vehiculo v = new Vehiculo(buscaMatricula.getText(), buscaMarca.getText(), buscaModelo.getText(), buscaCombustible.getText(), kilometraje,
                                            propietario.getDni(), seleccionSupervisor.getSelectedItem().toString());
                    this.vehiculo=v;
                    fa.nuevoVehiculo(v);
                    panelVehiculo.setEnabled(true);
                }
        }
    }//GEN-LAST:event_btnActualizarVehiculoActionPerformed

    private void LOCAL_actualizarVehiculo() {
        int kilometraje=0;
        if(!buscaKilometraje.getText().isBlank())
            kilometraje = Integer.parseInt(buscaKilometraje.getText());
            
        vehiculo.setMatricula(vehiculo.getMatricula());
        vehiculo.setMarca(buscaMarca.getText());
        vehiculo.setModelo(buscaModelo.getText());
        vehiculo.setCombustible(buscaCombustible.getText());
        vehiculo.setKilometraje(kilometraje);
        vehiculo.setPropietarioDNI(propietario.getDni());
        if (supervisor != null)
            vehiculo.setSupervisorID(supervisor.getIdMecanico());
    }
    
    private void seleccionarClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarClienteBotonActionPerformed
        eliminarClienteBoton.setEnabled(false);
        if(clienteseleccionado!=null) {
            buscaCliente.setText(clienteseleccionado.getNombre());
            propietario = clienteseleccionado;
        }
    }//GEN-LAST:event_seleccionarClienteBotonActionPerformed
    
    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // TODO add your handling code here:
        btnActualizarVehiculo.setEnabled(true);
        int filaSeleccionada= tablaClientes.getSelectedRow();
        ModeloTablaClientes mtl = (ModeloTablaClientes) tablaClientes.getModel();

        this.clienteseleccionado= mtl.obtenerCliente(filaSeleccionada);
        
        List<Vehiculo> vehiculosCliente = fa.obtenerVehiculosCliente(clienteseleccionado);
        int i = 0;
        if (vehiculosCliente == null) eliminarClienteBoton.setEnabled(true);
        else {
            for (Vehiculo v : vehiculosCliente) {
                if (fa.vehiculoTieneReparacionesPendientes(v)) i++;
            }
            if (i>0) eliminarClienteBoton.setEnabled(false);
            else eliminarClienteBoton.setEnabled(true);
        }

    }//GEN-LAST:event_tablaClientesMouseClicked

    private void anadirClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirClienteBotonActionPerformed
        VNuevoCliente vc = new VNuevoCliente(this, true, this.fa);
        vc.setVisible(true);
        buscarClientes();
    }//GEN-LAST:event_anadirClienteBotonActionPerformed

    private void eliminarClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteBotonActionPerformed
        fa.eliminarCliente(clienteseleccionado);
        btnActualizarVehiculo.setEnabled(false);
        eliminarClienteBoton.setEnabled(false);
        buscarClientes();
    }//GEN-LAST:event_eliminarClienteBotonActionPerformed

    private void gestionarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionarBotonActionPerformed
        int fila = TablaReparaciones.getSelectedRow();
        Integer idreparacion = (Integer) TablaReparaciones.getValueAt(fila, 0);
        
        VReparacion vr = new VReparacion(this, true, this.fa, idreparacion);
        vr.setVisible(true);
        gestionarBoton.setEnabled(false);
        buscarReparaciones();
    }//GEN-LAST:event_gestionarBotonActionPerformed

    private void anhadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirBotonActionPerformed
        VNuevaReparacion vnr = new VNuevaReparacion(this, true, this.fa, this.vehiculo, this.padre.getMecanicoApp());
        vnr.setVisible(true);
        buscarReparaciones();
    }//GEN-LAST:event_anhadirBotonActionPerformed

    private void TablaReparacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaReparacionesMouseClicked
        gestionarBoton.setEnabled(true);
    }//GEN-LAST:event_TablaReparacionesMouseClicked

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaReparaciones;
    private javax.swing.JButton anadirClienteBoton;
    private javax.swing.JButton anhadirBoton;
    private javax.swing.JButton btnActualizarVehiculo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField buscaCliente;
    private javax.swing.JTextField buscaCombustible;
    private javax.swing.JTextField buscaKilometraje;
    private javax.swing.JTextField buscaMarca;
    private javax.swing.JTextField buscaMatricula;
    private javax.swing.JTextField buscaModelo;
    private javax.swing.JButton eliminarClienteBoton;
    private javax.swing.JButton gestionarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelReparaciones;
    private javax.swing.JTabbedPane panelVehiculo;
    private javax.swing.JComboBox<String> seleccionSupervisor;
    private javax.swing.JButton seleccionarClienteBoton;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JScrollPane tablaReparaciones;
    // End of variables declaration//GEN-END:variables

    private void buscarClientes() {
        ModeloTablaClientes mc;
        List<Cliente> clientes= fa.obtenerClientes();
                
        mc=(ModeloTablaClientes) tablaClientes.getModel();
        mc.setFilas(clientes);
    }
    
    private void buscarReparaciones() {
        ModeloTablaReparaciones r;
        List<Reparacion> reparaciones = fa.obtenerReparaciones(vehiculo.getMatricula());

        r=(ModeloTablaReparaciones) TablaReparaciones.getModel();
        r.setFilas(reparaciones);
    }
}